/**
 * Pre-bundles game data from disk into a TypeScript module.
 * Run this before deploying to Cloudflare Workers where fs is unavailable.
 *
 * Usage: npx tsx scripts/bundle-game-data.ts
 * Output: src/games/_bundled-data.ts
 */
import { resolve, dirname } from "node:path";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { readGameDir } from "../src/games/read-game-dir.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const gamesDir = resolve(__dirname, "../src/games");
const outFile = resolve(gamesDir, "_bundled-data.ts");

const gameDirs = ["test-world", "colossal-cave", "the-aaru"];

const games = gameDirs.map((dir) => {
  const fullPath = resolve(gamesDir, dir);
  console.log(`Reading ${dir}...`);
  return readGameDir(fullPath);
});

const output = `// Auto-generated by scripts/bundle-game-data.ts — do not edit
import type { GameData } from "../core/game-data.js";

export const bundledGames: GameData[] = ${JSON.stringify(games, null, 2)};
`;

writeFileSync(outFile, output);
console.log(`Wrote ${outFile} (${gameDirs.length} games)`);
